enabled_exchanges = ["bitstamp", "binance"]

# Only one pair is supported at this point.
pair = "BTCUSDT"

####EXCHANGE CONFIGS####
# note: for now, we assume each have the same kind of ws api - an endpoint and subscription message.
# can implement specific details if/when needed.
# subscription messages are in a mustache template w/ the spot pair described.
[bitstamp]
endpoint = "wss://ws.bitstamp.net"
subscription_message_template = """{
    "event": "bts:subscribe",
    "data": {
        "channel": "order_book_{{pair}}"
    }
}"""
receive_timeout_s = 20

[binance]
endpoint = "wss://stream.binance.com:9443/ws"
subscription_message_template = """{
  "method": "SUBSCRIBE",
  "params": [
    "{{pair}}@depth10@100ms"
  ],
  "id": 1
}"""
receive_timeout_s = 1

#[bybit]
#endpoint = "wss://stream.bybit.com/realtime"
#subscription_message_template = """{"op": "subscribe", "args": ["orderBookL2_25.{{pair}}"]}"""
